project_id = "iflgryuemsohurtdaawm"

[functions.gerar-treino-ia]
verify_jwt = true

[functions.seed-alunos-demo]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.theme-ai]
verify_jwt = true

[functions.vlog-ingest]
verify_jwt = false
