// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Useful to verify MCP connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/list_athletes.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";

// src/lib/mcp/tools/_shared.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
var cached = null;
function getServiceClient() {
  if (cached) return cached;
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    throw new Error("SUPABASE_URL/SUPABASE_SERVICE_ROLE_KEY n\xE3o configurados no ambiente da fun\xE7\xE3o.");
  }
  cached = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
  return cached;
}
async function resolveTenant(mcpToken) {
  const empty = { ok: false, tenantId: "", tenantSlug: "", tenantName: null, error: "" };
  const token = (mcpToken ?? "").trim();
  if (!token) return { ...empty, error: "mcp_token obrigat\xF3rio." };
  const supa = getServiceClient();
  const { data, error } = await supa.from("tenants_private").select("tenant_id, tenants:tenant_id(slug, nome)").eq("mcp_token", token).maybeSingle();
  if (error) return { ...empty, error: `Falha ao validar token: ${error.message}` };
  if (!data) return { ...empty, error: "mcp_token inv\xE1lido." };
  const t = data.tenants;
  return {
    ok: true,
    tenantId: data.tenant_id,
    tenantSlug: t?.slug ?? "",
    tenantName: t?.nome ?? null,
    error: ""
  };
}
function extractBearerToken(extra) {
  try {
    const headers = extra?.requestInfo?.headers;
    if (headers) {
      const raw = typeof headers.get === "function" ? headers.get("authorization") : headers["authorization"];
      if (raw) {
        const match = /^Bearer\s+(.+)$/i.exec(String(raw).trim());
        return match ? match[1].trim() : String(raw).trim();
      }
    }
    if (typeof extra?.getToken === "function") {
      const token = extra.getToken();
      if (token) return String(token).trim();
    }
    return null;
  } catch {
    return null;
  }
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}
async function findAthlete(tenantId, ref) {
  const supa = getServiceClient();
  let q = supa.from("perfis").select("id, nome_completo, email, telefone, sexo, data_nascimento").eq("tenant_id", tenantId).limit(1);
  if (ref.athlete_id) q = q.eq("id", ref.athlete_id);
  else if (ref.email) q = q.ilike("email", ref.email.trim());
  else if (ref.nome) q = q.ilike("nome_completo", `%${ref.nome.trim()}%`);
  else return { error: "Informe athlete_id, email ou nome do aluno." };
  const { data, error } = await q.maybeSingle();
  if (error) return { error: error.message };
  if (!data) return { error: "Aluno n\xE3o encontrado neste tenant." };
  return { athlete: data };
}
async function resolveTenantByUser(userId) {
  const empty = { ok: false, tenantId: "", tenantSlug: "", tenantName: null, error: "" };
  if (!userId) return { ...empty, error: "Usu\xE1rio n\xE3o identificado no token." };
  const supa = getServiceClient();
  const owned = await supa.from("tenants").select("id, slug, nome").eq("owner_user_id", userId).limit(1).maybeSingle();
  if (owned.data) {
    const t = owned.data;
    return { ok: true, tenantId: t.id, tenantSlug: t.slug ?? "", tenantName: t.nome ?? null, error: "" };
  }
  const role = await supa.from("user_roles").select("tenant_id, role, tenants:tenant_id(slug, nome)").eq("user_id", userId).in("role", ["coach", "admin"]).not("tenant_id", "is", null).limit(1).maybeSingle();
  if (role.data) {
    const d = role.data;
    return {
      ok: true,
      tenantId: d.tenant_id,
      tenantSlug: d.tenants?.slug ?? "",
      tenantName: d.tenants?.nome ?? null,
      error: ""
    };
  }
  return { ...empty, error: "Esta conta n\xE3o \xE9 coach de nenhum tenant." };
}
async function resolveTenantForRequest(mcpToken, extra) {
  const userId = typeof extra?.getUserId === "function" ? extra.getUserId() : null;
  if (userId) {
    const byUser = await resolveTenantByUser(String(userId));
    if (byUser.ok) return byUser;
    if (!mcpToken) return byUser;
  }
  const token = mcpToken || extractBearerToken(extra) || "";
  return resolveTenant(token);
}

// src/lib/mcp/tools/list_athletes.ts
var list_athletes_default = defineTool2({
  name: "list_athletes",
  title: "Listar alunos",
  description: "Lista os alunos (perfis) vinculados ao tenant do coach. Retorna id, nome, email e telefone.",
  inputSchema: {
    mcp_token: z2.string().optional().describe("Token MCP do coach. Opcional se enviado via cabe\xE7alho Authorization: Bearer."),
    search: z2.string().optional().describe("Filtro opcional por nome ou email."),
    limit: z2.number().int().min(1).max(200).optional().describe("M\xE1ximo de resultados (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ mcp_token, search, limit }, extra) => {
    const auth2 = await resolveTenantForRequest(mcp_token, extra);
    if (!auth2.ok) return errorResult(auth2.error);
    const supa = getServiceClient();
    let q = supa.from("perfis").select("id, nome_completo, email, telefone, sexo, data_nascimento, onboarding_completo").eq("tenant_id", auth2.tenantId).order("nome_completo", { ascending: true }).limit(limit ?? 50);
    if (search && search.trim()) {
      const s = `%${search.trim()}%`;
      q = q.or(`nome_completo.ilike.${s},email.ilike.${s}`);
    }
    const { data, error } = await q;
    if (error) return errorResult(`Erro consultando alunos: ${error.message}`);
    return jsonResult({ tenant: auth2.tenantName, total: data?.length ?? 0, alunos: data ?? [] });
  }
});

// src/lib/mcp/tools/get_athlete_workout.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var DIAS = ["segunda", "terca", "quarta", "quinta", "sexta", "sabado", "domingo"];
var get_athlete_workout_default = defineTool3({
  name: "get_athlete_workout",
  title: "Consultar treino do aluno",
  description: "Retorna os exerc\xEDcios prescritos para um aluno. Filtre por dia da semana (segunda, terca, ...) se quiser apenas o treino do dia.",
  inputSchema: {
    mcp_token: z3.string().optional().describe("Token MCP do coach. Opcional se enviado via cabe\xE7alho Authorization: Bearer."),
    athlete_id: z3.string().uuid().optional(),
    email: z3.string().optional(),
    nome: z3.string().optional(),
    dia_semana: z3.enum(DIAS).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ mcp_token, athlete_id, email, nome, dia_semana }, extra) => {
    const auth2 = await resolveTenantForRequest(mcp_token, extra);
    if (!auth2.ok) return errorResult(auth2.error);
    const found = await findAthlete(auth2.tenantId, { athlete_id, email, nome });
    if ("error" in found) return errorResult(found.error);
    const supa = getServiceClient();
    let q = supa.from("treinos_prescritos").select("dia_semana, ordem, exercicio, series, repeticoes, cadencia, observacao, status, detalhes_execucao").eq("aluno_id", found.athlete.id).eq("tenant_id", auth2.tenantId).order("dia_semana").order("ordem");
    if (dia_semana) q = q.eq("dia_semana", dia_semana);
    const { data, error } = await q;
    if (error) return errorResult(`Erro consultando treino: ${error.message}`);
    return jsonResult({ aluno: found.athlete, dia_semana: dia_semana ?? "todos", exercicios: data ?? [] });
  }
});

// src/lib/mcp/tools/get_athlete_diet.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var get_athlete_diet_default = defineTool4({
  name: "get_athlete_diet",
  title: "Consultar dieta do aluno",
  description: "Retorna a dieta publicada do aluno com objetivo, kcal alvo, macros, refei\xE7\xF5es, hor\xE1rios e alimentos de cada refei\xE7\xE3o.",
  inputSchema: {
    mcp_token: z4.string().optional().describe("Token MCP do coach. Opcional se enviado via cabe\xE7alho Authorization: Bearer."),
    athlete_id: z4.string().uuid().optional(),
    email: z4.string().optional(),
    nome: z4.string().optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ mcp_token, athlete_id, email, nome }, extra) => {
    const auth2 = await resolveTenantForRequest(mcp_token, extra);
    if (!auth2.ok) return errorResult(auth2.error);
    const found = await findAthlete(auth2.tenantId, { athlete_id, email, nome });
    if ("error" in found) return errorResult(found.error);
    const supa = getServiceClient();
    const { data: dieta, error } = await supa.from("dietas").select("id, objetivo, tmb_estimada, kcal_alvo, macros_alvo, observacoes_clinicas, is_published, created_at").eq("user_id", found.athlete.id).order("created_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return errorResult(`Erro consultando dieta: ${error.message}`);
    if (!dieta) return jsonResult({ aluno: found.athlete, dieta: null, refeicoes: [] });
    const { data: refeicoes } = await supa.from("refeicoes").select("id, nome, horario, ordem, descricao_ia").eq("dieta_id", dieta.id).order("ordem");
    const ids = (refeicoes ?? []).map((r) => r.id);
    let itens = [];
    if (ids.length) {
      const { data: it } = await supa.from("itens_refeicao").select("refeicao_id, quantidade_g, substituicoes, alimento_id, alimentos_taco:alimento_id(nome, kcal_100g, proteina_g, carbo_g, gordura_g)").in("refeicao_id", ids);
      itens = it ?? [];
    }
    return jsonResult({ aluno: found.athlete, dieta, refeicoes: refeicoes ?? [], itens });
  }
});

// src/lib/mcp/tools/get_athlete_progress.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var get_athlete_progress_default = defineTool5({
  name: "get_athlete_progress",
  title: "Consultar evolu\xE7\xE3o do aluno",
  description: "Retorna as m\xE9tricas de evolu\xE7\xE3o do aluno: check-ins (peso, BF%, medidas) e avalia\xE7\xF5es f\xEDsicas recentes com composi\xE7\xE3o corporal. Ideal para acompanhar cutting/bulking.",
  inputSchema: {
    mcp_token: z5.string().optional().describe("Token MCP do coach. Opcional se enviado via cabe\xE7alho Authorization: Bearer."),
    athlete_id: z5.string().uuid().optional(),
    email: z5.string().optional(),
    nome: z5.string().optional(),
    checkin_limit: z5.number().int().min(1).max(60).optional().describe("Quantidade de check-ins recentes (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ mcp_token, athlete_id, email, nome, checkin_limit }, extra) => {
    const auth2 = await resolveTenantForRequest(mcp_token, extra);
    if (!auth2.ok) return errorResult(auth2.error);
    const found = await findAthlete(auth2.tenantId, { athlete_id, email, nome });
    if ("error" in found) return errorResult(found.error);
    const supa = getServiceClient();
    const limit = checkin_limit ?? 20;
    const [checkinsRes, avaliacoesRes, perfilTreinoRes] = await Promise.all([
      supa.from("evolucao_checkins").select("data_checkin, peso_kg, bf_percentual, massa_magra_kg, massa_gorda_kg, observacoes").eq("user_id", found.athlete.id).order("data_checkin", { ascending: false }).limit(limit),
      supa.from("avaliacoes_fisicas").select(
        "data, peso_kg, altura_cm, bf_pct_calculado, imc, massa_magra_kg, massa_gorda_kg, cintura_cm, quadril_cm, pescoco_cm, perimetro_braco_contraido_dir, perimetro_coxa_media_dir, metodo"
      ).eq("aluno_id", found.athlete.id).eq("tenant_id", auth2.tenantId).order("data", { ascending: false }).limit(10),
      supa.from("perfis_treino").select("objetivo, peso_kg, altura_cm, bf_pct, frequencia_semanal, tempo_treino").eq("aluno_id", found.athlete.id).maybeSingle()
    ]);
    const checkins = checkinsRes.data ?? [];
    let delta = null;
    if (checkins.length >= 2) {
      const last = checkins[0];
      const first = checkins[checkins.length - 1];
      const dias = Math.max(
        1,
        Math.round(
          (new Date(last.data_checkin).getTime() - new Date(first.data_checkin).getTime()) / 864e5
        )
      );
      const dPeso = last.peso_kg != null && first.peso_kg != null ? Number(last.peso_kg) - Number(first.peso_kg) : null;
      const dBf = last.bf_percentual != null && first.bf_percentual != null ? Number(last.bf_percentual) - Number(first.bf_percentual) : null;
      delta = {
        dias,
        delta_peso_kg: dPeso,
        delta_bf_pp: dBf,
        ritmo_semanal_kg: dPeso != null ? dPeso / dias * 7 : null
      };
    }
    return jsonResult({
      aluno: found.athlete,
      perfil_treino: perfilTreinoRes.data,
      resumo: delta,
      checkins,
      avaliacoes_fisicas: avaliacoesRes.data ?? []
    });
  }
});

// src/lib/mcp/tools/get_athlete_anamnesis.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z6 } from "npm:zod@^3.25.76";
var get_athlete_anamnesis_default = defineTool6({
  name: "get_athlete_anamnesis",
  title: "Consultar anamnese do aluno",
  description: "Retorna a anamnese completa do aluno: hist\xF3rico de sa\xFAde, sono, estresse, alimenta\xE7\xE3o, suplementos, treino e ergog\xEAnicos.",
  inputSchema: {
    mcp_token: z6.string().optional().describe("Token MCP do coach. Opcional se enviado via cabe\xE7alho Authorization: Bearer."),
    athlete_id: z6.string().uuid().optional(),
    email: z6.string().optional(),
    nome: z6.string().optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ mcp_token, athlete_id, email, nome }, extra) => {
    const auth2 = await resolveTenantForRequest(mcp_token, extra);
    if (!auth2.ok) return errorResult(auth2.error);
    const found = await findAthlete(auth2.tenantId, { athlete_id, email, nome });
    if ("error" in found) return errorResult(found.error);
    const supa = getServiceClient();
    const { data, error } = await supa.from("anamnese_aluno").select("*").eq("aluno_id", found.athlete.id).maybeSingle();
    if (error) return errorResult(`Erro consultando anamnese: ${error.message}`);
    return jsonResult({ aluno: found.athlete, anamnese: data });
  }
});

// src/lib/mcp/tools/add_athlete.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z7 } from "npm:zod@^3.25.76";
var add_athlete_default = defineTool7({
  name: "add_athlete",
  title: "Adicionar aluno",
  description: "Cria um novo aluno no tenant do coach. Envia convite por e-mail com senha tempor\xE1ria para que o aluno complete o onboarding no app.",
  inputSchema: {
    mcp_token: z7.string().optional().describe("Token MCP do coach. Opcional se enviado via cabe\xE7alho Authorization: Bearer."),
    nome_completo: z7.string().min(2).describe("Nome completo do aluno."),
    email: z7.string().describe("E-mail do aluno."),
    telefone: z7.string().optional(),
    sexo: z7.enum(["masculino", "feminino"]).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ mcp_token, nome_completo, email, telefone, sexo }, extra) => {
    const auth2 = await resolveTenantForRequest(mcp_token, extra);
    if (!auth2.ok) return errorResult(auth2.error);
    const supa = getServiceClient();
    const normalizedEmail = email.trim().toLowerCase();
    const { data: existing } = await supa.from("perfis").select("id, tenant_id").ilike("email", normalizedEmail).maybeSingle();
    if (existing) {
      if (existing.tenant_id === auth2.tenantId) {
        return errorResult(`Aluno ${normalizedEmail} j\xE1 est\xE1 cadastrado neste tenant (id=${existing.id}).`);
      }
      return errorResult(`E-mail j\xE1 cadastrado em outro tenant.`);
    }
    const tempPassword = crypto.randomUUID().replace(/-/g, "").slice(0, 12) + "A1!";
    const { data: created, error: createErr } = await supa.auth.admin.createUser({
      email: normalizedEmail,
      password: tempPassword,
      email_confirm: true,
      user_metadata: {
        nome_completo,
        tenant_id: auth2.tenantId,
        sexo: sexo ?? null,
        telefone: telefone ?? null
      }
    });
    if (createErr || !created?.user) {
      return errorResult(`Falha ao criar aluno: ${createErr?.message ?? "sem detalhes"}`);
    }
    const userId = created.user.id;
    await supa.from("perfis").update({ telefone: telefone ?? null, sexo: sexo ?? null, nome_completo }).eq("id", userId);
    await supa.from("user_roles").upsert({ user_id: userId, role: "aluno", tenant_id: auth2.tenantId }, { onConflict: "user_id,role,tenant_id" });
    return jsonResult({
      ok: true,
      aluno: { id: userId, nome_completo, email: normalizedEmail, tenant: auth2.tenantName },
      senha_temporaria: tempPassword,
      instrucoes: "Compartilhe a senha tempor\xE1ria com o aluno. Ele deve fazer login no app, alterar a senha e concluir o onboarding."
    });
  }
});

// src/lib/mcp/tools/set_athlete_workout.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z8 } from "npm:zod@^3.25.76";
var DIAS2 = ["segunda", "terca", "quarta", "quinta", "sexta", "sabado", "domingo"];
var exercicioSchema = z8.object({
  exercicio: z8.string().min(1).describe("Nome do exerc\xEDcio."),
  series: z8.string().optional().describe('Ex: "4".'),
  repeticoes: z8.string().optional().describe('Ex: "8-10".'),
  cadencia: z8.string().optional(),
  observacao: z8.string().optional(),
  detalhes_execucao: z8.string().optional(),
  video_url: z8.string().optional()
});
var set_athlete_workout_default = defineTool8({
  name: "set_athlete_workout",
  title: "Definir treino do dia",
  description: "Substitui (sobrescreve) o treino de um dia da semana do aluno pela lista de exerc\xEDcios enviada. Use replace=false para apenas acrescentar exerc\xEDcios ao final do dia.",
  inputSchema: {
    mcp_token: z8.string().optional().describe("Token MCP do coach. Opcional se enviado via Authorization: Bearer."),
    athlete_id: z8.string().uuid().optional(),
    email: z8.string().optional(),
    nome: z8.string().optional(),
    dia_semana: z8.enum(DIAS2),
    replace: z8.boolean().optional().describe("Padr\xE3o true: apaga os exerc\xEDcios existentes do dia antes de inserir."),
    exercicios: z8.array(exercicioSchema).min(1).describe("Lista de exerc\xEDcios na ordem desejada.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ mcp_token, athlete_id, email, nome, dia_semana, replace, exercicios }, extra) => {
    const auth2 = await resolveTenantForRequest(mcp_token, extra);
    if (!auth2.ok) return errorResult(auth2.error);
    const found = await findAthlete(auth2.tenantId, { athlete_id, email, nome });
    if ("error" in found) return errorResult(found.error);
    const supa = getServiceClient();
    let startOrder = 0;
    if (replace === false) {
      const { data: last } = await supa.from("treinos_prescritos").select("ordem").eq("aluno_id", found.athlete.id).eq("tenant_id", auth2.tenantId).eq("dia_semana", dia_semana).order("ordem", { ascending: false }).limit(1).maybeSingle();
      startOrder = Number(last?.ordem ?? 0);
    } else {
      const { error: delErr } = await supa.from("treinos_prescritos").delete().eq("aluno_id", found.athlete.id).eq("tenant_id", auth2.tenantId).eq("dia_semana", dia_semana);
      if (delErr) return errorResult(`Erro limpando treino do dia: ${delErr.message}`);
    }
    async function lookupVideo(nome2) {
      const like = `%${nome2.trim()}%`;
      const ref = await supa.from("referencia_exercicios").select("url_video, tenant_id").ilike("nome_exercicio", like).or(`tenant_id.eq.${auth2.tenantId},tenant_id.is.null`).order("tenant_id", { ascending: true, nullsFirst: false }).limit(1).maybeSingle();
      const refUrl = ref.data?.url_video;
      if (refUrl) return refUrl;
      const vid = await supa.from("referencia_videos").select("url_video").ilike("nome_exercicio", like).or(`tenant_id.eq.${auth2.tenantId},tenant_id.is.null`).limit(1).maybeSingle();
      return vid.data?.url_video ?? null;
    }
    const rows = await Promise.all(
      exercicios.map(async (ex, i) => ({
        tenant_id: auth2.tenantId,
        aluno_id: found.athlete.id,
        dia_semana,
        ordem: startOrder + i + 1,
        exercicio: ex.exercicio,
        series: ex.series ?? null,
        repeticoes: ex.repeticoes ?? null,
        cadencia: ex.cadencia ?? null,
        observacao: ex.observacao ?? null,
        detalhes_execucao: ex.detalhes_execucao ?? null,
        video_url: ex.video_url ?? await lookupVideo(ex.exercicio),
        status: "ativo"
      }))
    );
    const { data, error } = await supa.from("treinos_prescritos").insert(rows).select("id, ordem, exercicio");
    if (error) return errorResult(`Erro salvando treino: ${error.message}`);
    return jsonResult({
      ok: true,
      aluno: found.athlete,
      dia_semana,
      modo: replace === false ? "acrescentado" : "substituido",
      total: data?.length ?? 0,
      exercicios: data ?? []
    });
  }
});

// src/lib/mcp/tools/update_workout_exercise.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z9 } from "npm:zod@^3.25.76";
var DIAS3 = ["segunda", "terca", "quarta", "quinta", "sexta", "sabado", "domingo"];
var update_workout_exercise_default = defineTool9({
  name: "update_workout_exercise",
  title: "Editar exerc\xEDcio do treino",
  description: "Edita um exerc\xEDcio j\xE1 prescrito (s\xE9ries, repeti\xE7\xF5es, cad\xEAncia, observa\xE7\xE3o, nome ou v\xEDdeo). Identifique pelo exercise_id (retornado por get_athlete_workout) ou pelo nome do exerc\xEDcio + dia da semana.",
  inputSchema: {
    mcp_token: z9.string().optional().describe("Token MCP do coach. Opcional se enviado via Authorization: Bearer."),
    exercise_id: z9.string().uuid().optional().describe("ID da linha em treinos_prescritos."),
    athlete_id: z9.string().uuid().optional(),
    email: z9.string().optional(),
    nome: z9.string().optional(),
    dia_semana: z9.enum(DIAS3).optional(),
    exercicio_atual: z9.string().optional().describe("Nome (ou parte) do exerc\xEDcio a editar, quando n\xE3o usar exercise_id."),
    novo_exercicio: z9.string().optional(),
    series: z9.string().optional(),
    repeticoes: z9.string().optional(),
    cadencia: z9.string().optional(),
    observacao: z9.string().optional(),
    detalhes_execucao: z9.string().optional(),
    video_url: z9.string().optional(),
    ordem: z9.number().int().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, extra) => {
    const auth2 = await resolveTenantForRequest(input.mcp_token, extra);
    if (!auth2.ok) return errorResult(auth2.error);
    const supa = getServiceClient();
    const patch = {};
    if (input.novo_exercicio !== void 0) patch.exercicio = input.novo_exercicio;
    if (input.series !== void 0) patch.series = input.series;
    if (input.repeticoes !== void 0) patch.repeticoes = input.repeticoes;
    if (input.cadencia !== void 0) patch.cadencia = input.cadencia;
    if (input.observacao !== void 0) patch.observacao = input.observacao;
    if (input.detalhes_execucao !== void 0) patch.detalhes_execucao = input.detalhes_execucao;
    if (input.video_url !== void 0) patch.video_url = input.video_url;
    if (input.ordem !== void 0) patch.ordem = input.ordem;
    if (Object.keys(patch).length === 0) return errorResult("Informe ao menos um campo para alterar.");
    patch.updated_at = (/* @__PURE__ */ new Date()).toISOString();
    let q = supa.from("treinos_prescritos").update(patch).eq("tenant_id", auth2.tenantId);
    if (input.exercise_id) {
      q = q.eq("id", input.exercise_id);
    } else {
      const found = await findAthlete(auth2.tenantId, {
        athlete_id: input.athlete_id,
        email: input.email,
        nome: input.nome
      });
      if ("error" in found) return errorResult(found.error);
      if (!input.exercicio_atual) return errorResult("Informe exercise_id ou exercicio_atual.");
      q = q.eq("aluno_id", found.athlete.id).ilike("exercicio", `%${input.exercicio_atual.trim()}%`);
      if (input.dia_semana) q = q.eq("dia_semana", input.dia_semana);
    }
    const { data, error } = await q.select("id, dia_semana, ordem, exercicio, series, repeticoes, cadencia, observacao");
    if (error) return errorResult(`Erro atualizando exerc\xEDcio: ${error.message}`);
    if (!data || data.length === 0) return errorResult("Nenhum exerc\xEDcio encontrado com esses crit\xE9rios.");
    return jsonResult({ ok: true, atualizados: data.length, exercicios: data });
  }
});

// src/lib/mcp/tools/delete_workout_exercise.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z10 } from "npm:zod@^3.25.76";
var DIAS4 = ["segunda", "terca", "quarta", "quinta", "sexta", "sabado", "domingo"];
var delete_workout_exercise_default = defineTool10({
  name: "delete_workout_exercise",
  title: "Remover exerc\xEDcio do treino",
  description: "Remove exerc\xEDcios prescritos do aluno. Use exercise_id para remover um espec\xEDfico, ou dia_semana (+ opcionalmente exercicio) para remover do dia.",
  inputSchema: {
    mcp_token: z10.string().optional().describe("Token MCP do coach. Opcional se enviado via Authorization: Bearer."),
    exercise_id: z10.string().uuid().optional(),
    athlete_id: z10.string().uuid().optional(),
    email: z10.string().optional(),
    nome: z10.string().optional(),
    dia_semana: z10.enum(DIAS4).optional(),
    exercicio: z10.string().optional().describe("Nome (ou parte) do exerc\xEDcio a remover.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ mcp_token, exercise_id, athlete_id, email, nome, dia_semana, exercicio }, extra) => {
    const auth2 = await resolveTenantForRequest(mcp_token, extra);
    if (!auth2.ok) return errorResult(auth2.error);
    const supa = getServiceClient();
    let q = supa.from("treinos_prescritos").delete().eq("tenant_id", auth2.tenantId);
    if (exercise_id) {
      q = q.eq("id", exercise_id);
    } else {
      const found = await findAthlete(auth2.tenantId, { athlete_id, email, nome });
      if ("error" in found) return errorResult(found.error);
      if (!dia_semana && !exercicio) {
        return errorResult("Informe exercise_id, ou dia_semana e/ou exercicio para evitar apagar tudo.");
      }
      q = q.eq("aluno_id", found.athlete.id);
      if (dia_semana) q = q.eq("dia_semana", dia_semana);
      if (exercicio) q = q.ilike("exercicio", `%${exercicio.trim()}%`);
    }
    const { data, error } = await q.select("id, dia_semana, exercicio");
    if (error) return errorResult(`Erro removendo exerc\xEDcio: ${error.message}`);
    return jsonResult({ ok: true, removidos: data?.length ?? 0, exercicios: data ?? [] });
  }
});

// src/lib/mcp/tools/set_athlete_diet.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z11 } from "npm:zod@^3.25.76";
var itemSchema = z11.object({
  alimento: z11.string().min(1).describe("Nome do alimento (busca na base TACO; se n\xE3o achar, entra como texto na descri\xE7\xE3o)."),
  quantidade_g: z11.number().positive().optional(),
  substituicoes: z11.string().optional()
});
var refeicaoSchema = z11.object({
  nome: z11.string().min(1).describe('Ex: "Caf\xE9 da manh\xE3".'),
  horario: z11.string().optional().describe('Formato HH:MM, ex: "07:30".'),
  descricao_ia: z11.string().optional().describe("Descri\xE7\xE3o livre da refei\xE7\xE3o."),
  itens: z11.array(itemSchema).optional()
});
var set_athlete_diet_default = defineTool11({
  name: "set_athlete_diet",
  title: "Montar dieta do aluno",
  description: "Cria e publica uma nova dieta para o aluno, com objetivo, kcal alvo, macros e refei\xE7\xF5es (com hor\xE1rios e alimentos). Substitui a dieta anterior como a mais recente.",
  inputSchema: {
    mcp_token: z11.string().optional().describe("Token MCP do coach. Opcional se enviado via Authorization: Bearer."),
    athlete_id: z11.string().uuid().optional(),
    email: z11.string().optional(),
    nome: z11.string().optional(),
    objetivo: z11.string().optional().describe('Ex: "emagrecimento", "hipertrofia".'),
    kcal_alvo: z11.number().positive().optional(),
    macros_alvo: z11.object({ proteina_g: z11.number().optional(), carbo_g: z11.number().optional(), gordura_g: z11.number().optional() }).optional(),
    observacoes_clinicas: z11.string().optional(),
    publicar: z11.boolean().optional().describe("Padr\xE3o true: j\xE1 publica a dieta para o aluno."),
    refeicoes: z11.array(refeicaoSchema).min(1)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, extra) => {
    const auth2 = await resolveTenantForRequest(input.mcp_token, extra);
    if (!auth2.ok) return errorResult(auth2.error);
    const found = await findAthlete(auth2.tenantId, {
      athlete_id: input.athlete_id,
      email: input.email,
      nome: input.nome
    });
    if ("error" in found) return errorResult(found.error);
    const supa = getServiceClient();
    const { data: dieta, error: dietaErr } = await supa.from("dietas").insert({
      user_id: found.athlete.id,
      objetivo: input.objetivo ?? null,
      kcal_alvo: input.kcal_alvo ?? null,
      macros_alvo: input.macros_alvo ?? null,
      observacoes_clinicas: input.observacoes_clinicas ?? null,
      is_published: input.publicar !== false
    }).select("id").single();
    if (dietaErr || !dieta) return errorResult(`Erro criando dieta: ${dietaErr?.message ?? "sem detalhes"}`);
    const dietaId = dieta.id;
    const criadas = [];
    for (let i = 0; i < input.refeicoes.length; i++) {
      const r = input.refeicoes[i];
      const { data: ref, error: refErr } = await supa.from("refeicoes").insert({
        dieta_id: dietaId,
        nome: r.nome,
        horario: r.horario ?? null,
        ordem: i + 1,
        descricao_ia: r.descricao_ia ?? null
      }).select("id").single();
      if (refErr || !ref) return errorResult(`Erro criando refei\xE7\xE3o "${r.nome}": ${refErr?.message ?? ""}`);
      const refId = ref.id;
      const itens = r.itens ?? [];
      let inseridos = 0;
      for (const it of itens) {
        const { data: alimento } = await supa.from("alimentos_taco").select("id").ilike("nome", `%${it.alimento.trim()}%`).limit(1).maybeSingle();
        const alimentoId = alimento?.id ?? null;
        const sub = alimentoId ? it.substituicoes ?? null : [it.alimento, it.substituicoes].filter(Boolean).join(" \u2014 ");
        const { error: itemErr } = await supa.from("itens_refeicao").insert({
          refeicao_id: refId,
          alimento_id: alimentoId,
          quantidade_g: it.quantidade_g ?? null,
          substituicoes: sub || null
        });
        if (!itemErr) inseridos++;
      }
      criadas.push({ id: refId, nome: r.nome, itens: inseridos });
    }
    return jsonResult({
      ok: true,
      aluno: found.athlete,
      dieta_id: dietaId,
      publicada: input.publicar !== false,
      refeicoes: criadas
    });
  }
});

// src/lib/mcp/tools/list_exercise_library.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z12 } from "npm:zod@^3.25.76";
var list_exercise_library_default = defineTool12({
  name: "list_exercise_library",
  title: "Listar biblioteca de exerc\xEDcios e v\xEDdeos t\xE9cnicos",
  description: "Lista os exerc\xEDcios e v\xEDdeos t\xE9cnicos dispon\xEDveis para o coach (tabelas referencia_exercicios, referencia_videos e biblioteca_exercicios), incluindo v\xEDdeos globais do app. Use antes de montar treino para escolher exerc\xEDcios com v\xEDdeo j\xE1 cadastrado.",
  inputSchema: {
    mcp_token: z12.string().optional().describe("Token MCP do coach. Opcional se enviado via Authorization: Bearer."),
    search: z12.string().optional().describe("Filtro por nome do exerc\xEDcio."),
    grupo_muscular: z12.string().optional().describe("Filtro por grupamento muscular."),
    apenas_meus: z12.boolean().optional().describe("Padr\xE3o false: inclui tamb\xE9m os v\xEDdeos globais do app."),
    limit: z12.number().int().min(1).max(300).optional().describe("M\xE1ximo por tabela (padr\xE3o 100).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ mcp_token, search, grupo_muscular, apenas_meus, limit }, extra) => {
    const auth2 = await resolveTenantForRequest(mcp_token, extra);
    if (!auth2.ok) return errorResult(auth2.error);
    const supa = getServiceClient();
    const max = limit ?? 100;
    const tenantFilter = (col = "tenant_id") => apenas_meus ? `${col}.eq.${auth2.tenantId}` : `${col}.eq.${auth2.tenantId},${col}.is.null`;
    let refQ = supa.from("referencia_exercicios").select("id, nome_exercicio, url_video, thumbnail_url, grupamento_muscular, tenant_id, origem").or(tenantFilter()).order("nome_exercicio").limit(max);
    if (search?.trim()) refQ = refQ.ilike("nome_exercicio", `%${search.trim()}%`);
    if (grupo_muscular?.trim()) refQ = refQ.ilike("grupamento_muscular", `%${grupo_muscular.trim()}%`);
    let vidQ = supa.from("referencia_videos").select("id, nome_exercicio, url_video, video_coach_url, tenant_id").or(tenantFilter()).order("nome_exercicio").limit(max);
    if (search?.trim()) vidQ = vidQ.ilike("nome_exercicio", `%${search.trim()}%`);
    let bibQ = supa.from("biblioteca_exercicios").select("id, nome, grupo_muscular, equipamento, nivel, series_trabalho, repeticoes, contraindicacoes, video_url, video_coach_url, tenant_id").or(tenantFilter()).order("nome").limit(max);
    if (search?.trim()) bibQ = bibQ.ilike("nome", `%${search.trim()}%`);
    if (grupo_muscular?.trim()) bibQ = bibQ.ilike("grupo_muscular", `%${grupo_muscular.trim()}%`);
    const [ref, vid, bib] = await Promise.all([refQ, vidQ, bibQ]);
    const erro = ref.error?.message ?? vid.error?.message ?? bib.error?.message;
    if (erro) return errorResult(`Erro consultando biblioteca: ${erro}`);
    return jsonResult({
      tenant: auth2.tenantName,
      referencia_exercicios: ref.data ?? [],
      referencia_videos: vid.data ?? [],
      biblioteca_exercicios: bib.data ?? [],
      totais: {
        referencia_exercicios: ref.data?.length ?? 0,
        referencia_videos: vid.data?.length ?? 0,
        biblioteca_exercicios: bib.data?.length ?? 0
      }
    });
  }
});

// src/lib/mcp/tools/update_athlete_workout.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z13 } from "npm:zod@^3.25.76";
var DIAS5 = ["segunda", "terca", "quarta", "quinta", "sexta", "sabado", "domingo"];
var update_athlete_workout_default = defineTool13({
  name: "update_athlete_workout",
  title: "Criar/editar/remover exerc\xEDcio do treino",
  description: "Cria, atualiza ou remove um exerc\xEDcio prescrito do aluno. Use action='upsert' (com exercise_id para editar, sem ele para criar) ou action='delete' (exige exercise_id).",
  inputSchema: {
    mcp_token: z13.string().optional().describe("Token MCP do coach. Opcional se enviado via Authorization: Bearer."),
    athlete_id: z13.string().uuid().optional(),
    email: z13.string().optional(),
    nome: z13.string().optional(),
    action: z13.enum(["upsert", "delete"]).describe("upsert = criar/editar; delete = remover."),
    exercise_id: z13.string().uuid().optional().describe("ID da linha em treinos_prescritos."),
    dia_semana: z13.enum(DIAS5).optional().describe("Obrigat\xF3rio ao criar um novo exerc\xEDcio."),
    exercicio: z13.string().optional().describe("Nome do exerc\xEDcio. Obrigat\xF3rio ao criar."),
    series: z13.string().optional(),
    repeticoes: z13.string().optional(),
    observacao: z13.string().optional(),
    cadencia: z13.string().optional(),
    detalhes_execucao: z13.string().optional(),
    ordem: z13.number().int().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async (input, extra) => {
    const auth2 = await resolveTenantForRequest(input.mcp_token, extra);
    if (!auth2.ok) return errorResult(auth2.error);
    const found = await findAthlete(auth2.tenantId, {
      athlete_id: input.athlete_id,
      email: input.email,
      nome: input.nome
    });
    if ("error" in found) return errorResult(found.error);
    const supa = getServiceClient();
    const alunoId = found.athlete.id;
    const SELECT = "id, dia_semana, ordem, exercicio, series, repeticoes, cadencia, observacao, detalhes_execucao, status";
    if (input.action === "delete") {
      if (!input.exercise_id) return errorResult("Informe exercise_id para remover um exerc\xEDcio.");
      const { data: data2, error: error2 } = await supa.from("treinos_prescritos").delete().eq("id", input.exercise_id).eq("tenant_id", auth2.tenantId).eq("aluno_id", alunoId).select(SELECT);
      if (error2) return errorResult(`Erro removendo exerc\xEDcio: ${error2.message}`);
      if (!data2 || data2.length === 0) return errorResult("Exerc\xEDcio n\xE3o encontrado para este aluno/tenant.");
      return jsonResult({ ok: true, acao: "removido", aluno: found.athlete, exercicio: data2[0] });
    }
    if (input.exercise_id) {
      const patch = {};
      if (input.dia_semana !== void 0) patch.dia_semana = input.dia_semana;
      if (input.exercicio !== void 0) patch.exercicio = input.exercicio;
      if (input.series !== void 0) patch.series = input.series;
      if (input.repeticoes !== void 0) patch.repeticoes = input.repeticoes;
      if (input.observacao !== void 0) patch.observacao = input.observacao;
      if (input.cadencia !== void 0) patch.cadencia = input.cadencia;
      if (input.detalhes_execucao !== void 0) patch.detalhes_execucao = input.detalhes_execucao;
      if (input.ordem !== void 0) patch.ordem = input.ordem;
      if (Object.keys(patch).length === 0) return errorResult("Informe ao menos um campo para alterar.");
      patch.updated_at = (/* @__PURE__ */ new Date()).toISOString();
      const { data: data2, error: error2 } = await supa.from("treinos_prescritos").update(patch).eq("id", input.exercise_id).eq("tenant_id", auth2.tenantId).eq("aluno_id", alunoId).select(SELECT);
      if (error2) return errorResult(`Erro atualizando exerc\xEDcio: ${error2.message}`);
      if (!data2 || data2.length === 0) return errorResult("Exerc\xEDcio n\xE3o encontrado para este aluno/tenant.");
      return jsonResult({ ok: true, acao: "atualizado", aluno: found.athlete, exercicio: data2[0] });
    }
    if (!input.dia_semana) return errorResult("Informe dia_semana para criar um exerc\xEDcio.");
    if (!input.exercicio) return errorResult("Informe exercicio para criar um exerc\xEDcio.");
    let ordem = input.ordem;
    if (ordem === void 0) {
      const { data: last } = await supa.from("treinos_prescritos").select("ordem").eq("tenant_id", auth2.tenantId).eq("aluno_id", alunoId).eq("dia_semana", input.dia_semana).order("ordem", { ascending: false }).limit(1).maybeSingle();
      ordem = Number(last?.ordem ?? 0) + 1;
    }
    const { data, error } = await supa.from("treinos_prescritos").insert({
      tenant_id: auth2.tenantId,
      aluno_id: alunoId,
      dia_semana: input.dia_semana,
      exercicio: input.exercicio,
      series: input.series ?? null,
      repeticoes: input.repeticoes ?? null,
      observacao: input.observacao ?? null,
      cadencia: input.cadencia ?? null,
      detalhes_execucao: input.detalhes_execucao ?? null,
      ordem,
      status: "ativo"
    }).select(SELECT);
    if (error) return errorResult(`Erro criando exerc\xEDcio: ${error.message}`);
    return jsonResult({ ok: true, acao: "criado", aluno: found.athlete, exercicio: data?.[0] ?? null });
  }
});

// src/lib/mcp/index.ts
var projectRef = "iflgryuemsohurtdaawm";
var mcp_default = defineMcp({
  name: "alpha-coach-mcp",
  title: "Alpha Coach MCP",
  version: "0.3.0",
  instructions: "Servidor MCP do Alpha Coach. O coach conecta com a pr\xF3pria conta do painel (login OAuth); as ferramentas j\xE1 operam no tenant dele. Leitura: list_athletes, list_exercise_library (biblioteca de exerc\xEDcios e v\xEDdeos t\xE9cnicos), get_athlete_workout, get_athlete_diet, get_athlete_progress, get_athlete_anamnesis. Escrita: add_athlete (cadastrar aluno), set_athlete_workout (definir/substituir treino de um dia), update_athlete_workout (criar, editar ou remover um exerc\xEDcio individual via action upsert/delete), update_workout_exercise (editar s\xE9ries/reps/observa\xE7\xE3o), delete_workout_exercise (remover exerc\xEDcio), set_athlete_diet (montar e publicar dieta). Use echo para testar conectividade.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    echo_default,
    list_athletes_default,
    get_athlete_workout_default,
    get_athlete_diet_default,
    get_athlete_progress_default,
    get_athlete_anamnesis_default,
    add_athlete_default,
    set_athlete_workout_default,
    update_athlete_workout_default,
    update_workout_exercise_default,
    delete_workout_exercise_default,
    set_athlete_diet_default,
    list_exercise_library_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
