DELETE FROM public.templates_treino WHERE codigo IN ('ABCDE_CLASSICA_PACHO_INT','ABCDE_CLASSICA_PACHO_AV');

INSERT INTO public.templates_treino (codigo, titulo, publico, nivel, frequencia_semanal, divisao, enfase, objetivo, fonte_arquivo, resumo, conteudo_completo, tags, ativo)
VALUES
('ABCDE_CLASSICA_PACHO_INT','ABCDE 5x — Clássica Pacholok (Intermediário)','unisex','intermediario',5,'ABCDE','equilibrio','hipertrofia','manual_pacholok',
'Divisão clássica Pacholok 5x: Seg Peito+Tríceps+estímulo anterior de ombro / Ter Costas+Bíceps+estímulo posterior de ombro / Qua Perna ênfase quadríceps / Qui OFF / Sex Ombro completo / Sáb Perna ênfase posterior+glúteo / Dom OFF',
E'DIVISÃO ABCDE — CLÁSSICA PACHOLOK (5x/semana)\n\nSEG (A) — Peito + Tríceps + estímulo anterior de ombro\n  - Peito: 4 ex (supino reto, inclinado, declinado/cross, voador) — 3-4x 8-12\n  - Tríceps: 3 ex (testa, corda, francês) — 3x 10-12\n  - Estímulo anterior de ombro: 1 ex (elevação frontal) — 3x 12-15\n\nTER (B) — Costas + Bíceps + estímulo posterior de ombro\n  - Costas: 4-5 ex (puxada, remada curvada, remada baixa, pulldown) — 3-4x 8-12\n  - Bíceps: 3 ex (direta, alternada, scott) — 3x 10-12\n  - Estímulo posterior de ombro: 1 ex (crucifixo invertido ou face pull) — 3x 15\n\nQUA (C) — Perna ênfase QUADRÍCEPS\n  - Agachamento livre/hack — 4x 8-10\n  - Leg press 45º — 4x 10-12\n  - Extensora — 3-4x 12-15 (rest-pause na última)\n  - Avanço — 3x 12 cada perna\n  - Stiff leve OU mesa flexora — 3x 12 (volume menor para posterior)\n  - Panturrilha em pé — 4x 15-20\n\nQUI — OFF\n\nSEX (D) — Ombro completo\n  - Desenvolvimento — 4x 8-12\n  - Elevação lateral halter + polia — 4x 12-15 (drop na última)\n  - Crucifixo invertido + face pull — 3x 12-15\n  - Encolhimento — 3-4x 12-15\n\nSÁB (E) — Perna ênfase POSTERIOR + GLÚTEO\n  - Stiff — 4x 8-10\n  - Mesa flexora — 4x 10-12 (rest-pause na última)\n  - Flexora unilateral — 3x 12\n  - Hip thrust — 4x 10-12\n  - Glúteo polia/coice — 3x 15\n  - Sumô leve OU leg pés altos — 3x 12 (volume menor de quadríceps)\n  - Panturrilha sentado — 4x 15-20\n\nDOM — OFF\n\nPRINCÍPIOS PACHOLOK\n  - Cadência 3-0-2-0; excêntrica enfatizada\n  - Pausa: 60-90s hipertrofia / 90-120s compostos pesados\n  - Última série de isoladores: rest-pause ou drop\n  - 2 aquecimento + 1 ajuste antes das séries de trabalho em compostos\n  - Estímulo de ombro nos dias A/B é LEVE (1 ex, 3 séries) para não atrapalhar o dia D',
ARRAY['pacholok','abcde','5x','classica','peito-triceps','costas-biceps'], true),

('ABCDE_CLASSICA_PACHO_AV','ABCDE 5x — Clássica Pacholok (Avançado)','unisex','avancado',5,'ABCDE','equilibrio','hipertrofia','manual_pacholok',
'Versão avançada da divisão clássica Pacholok 5x com mais técnicas de intensidade (rest-pause, drop-set, FST-7, parciais).',
E'DIVISÃO ABCDE — CLÁSSICA PACHOLOK AVANÇADO (5x/semana)\n\nSEG (A) — Peito + Tríceps + estímulo anterior de ombro\n  - Peito: 5 ex — 4x 8-12, FST-7 finalizador (voador 7x10/30s)\n  - Tríceps: 3-4 ex — 4x 10-12, drop na última\n  - Estímulo anterior ombro: elevação frontal — 3x 15 + parciais\n\nTER (B) — Costas + Bíceps + estímulo posterior de ombro\n  - Costas: 5 ex — 4x 8-12, rest-pause em remada\n  - Bíceps: 3-4 ex — 4x, 21s ou drop na última\n  - Estímulo posterior ombro: face pull + crucifixo invertido — 3x 15\n\nQUA (C) — Perna ênfase QUADRÍCEPS\n  - Agachamento livre — 5x 6-10 (pirâmide)\n  - Hack 45º — 4x 10-12 (drop)\n  - Leg press — 4x 12-15 + rest-pause\n  - Extensora — FST-7 (7x10)\n  - Avanço — 3x 12\n  - Stiff leve — 3x10\n  - Panturrilha — 5x 15-20\n\nQUI — OFF\n\nSEX (D) — Ombro completo\n  - Desenvolvimento halter — 4x 8-10\n  - Desenvolvimento máquina — 3x 10-12 (drop)\n  - Elevação lateral halter — 4x 12 + 21s\n  - Lateral polia unilateral — FST-7\n  - Posterior na máquina/polia — 4x 12-15\n  - Encolhimento + remada alta — 4x 12\n\nSÁB (E) — Perna ênfase POSTERIOR + GLÚTEO\n  - Stiff — 5x 6-10\n  - Mesa flexora — 4x 10-12 + rest-pause\n  - Flexora unilateral — FST-7\n  - Hip thrust — 4x 8-10 pesado\n  - Glúteo polia/abdução — 4x 15\n  - Sumô/leg pés altos leve — 3x12\n  - Panturrilha sentado — 5x 15-20\n\nDOM — OFF\n\nTÉCNICAS DE INTENSIDADE OBRIGATÓRIAS\n  - Rest-pause em ≥ 1 composto/dia\n  - Drop-set na última série dos isoladores\n  - FST-7 em 1 grupo finalizador por treino\n  - Cadência 4-0-2-0 nos compostos / 3-0-1-1 com pico nos isoladores\n  - Pausa: 90-120s compostos / 45-60s isoladores e FST-7',
ARRAY['pacholok','abcde','5x','classica','avancado','rest-pause','fst-7'], true);